# Base image — Node.js version 18 on Alpine Linux. This is the container’s “operating system,” with Node already installed  
FROM node:18-alpine

# Metadata — identifies who created the image. Doesn’t affect functionality, purely documentation  
LABEL maintainer="NatyFerreira"

# Sets /app as the working directory inside the container. All following commands run from here. It’s like doing cd /app but permanently  
WORKDIR /app

# Copies files from your Mac into the image, into the /app directory  
COPY package.json .  
# The dot means “here” (the WORKDIR). package.json comes before app.js because Docker uses layer caching — if package.json hasn’t changed, it reuses the npm install layer without reinstalling everything  
COPY app.js .  
COPY .env .

# Runs during the image build. Installs the dependencies listed in package.json (express, axios, dotenv)  
RUN npm install

# Defines an environment variable available inside the container. app.js uses process.env.PORT to know which port to listen on  
ENV PORT=3000

COPY ./index.html /usr/share/nginx/html/  
EXPOSE 3000

# Command executed when the container starts. Runs npm start, which in turn executes node app.js. Unlike RUN, this does not execute during the build  
CMD ["npm", "start"]

# SUMMARY:
# docker build  →  FROM + LABEL + WORKDIR + COPY + RUN  (builds the image)  
# docker run    →  ENV + EXPOSE + CMD                    (starts the container)
